export  * from './admin-dashboard/admin-dashboard.component'
export  * from './hospital/hospital.component'
export * from './user/user.component'
export * from './vehicle/vehicle.component'
export * from './police/police.component'
export * from './fire-service/fire-service.component'
export * from './incident/incident.component'
